ead:
  serviceRegistry:
    username: serviceregistry
    password: 'serviceregistry'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'
